- name: Cleanup Script for Ansible
  hosts: localhost
  connection: local
  vars:
        unispherehost: '192.168.123.1'
        universion: "90"
        verifycert: False
        user: 'smc'
        password: 'smc'
        array_id: '000197600156'

  tasks:
  - name: Delete Masking View
    dellpmax_deletemaskingview:
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        verifycert: "{{verifycert}}"
        user: "{{user}}"
        password: "{{password}}"
        array_id: "{{array_id}}"
        maskingview_name: "Ansible_MV"
  - name: Delete Port Group
    dellpmax_deleteportgroup:
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        verifycert: "{{verifycert}}"
        user: "{{user}}"
        password: "{{password}}"
        array_id: "{{array_id}}"
        portgroup_id: "Ansible_PG"
  - name: Delete Hostgroup
    dellpmax_deletehostgroup:
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        verifycert: "{{verifycert}}"
        user: "{{user}}"
        password: "{{password}}"
        array_id: "{{array_id}}"
        host_or_cluster: "AnsibleCluster"
  - name: Delete Host
    dellpmax_deletehost:
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        verifycert: "{{verifycert}}"
        user: "{{user}}"
        password: "{{password}}"
        array_id: "{{array_id}}"
        host_or_cluster: "AnsibleHost1"
  - name: Delete Host
    dellpmax_deletehost:
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        verifycert: "{{verifycert}}"
        user: "{{user}}"
        password: "{{password}}"
        array_id: "{{array_id}}"
        host_or_cluster: "AnsibleHost2"
  - name: Delete Storage Group
    dellpmax_deletestoragegroup:
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        verifycert: "{{verifycert}}"
        user: "{{user}}"
        password: "{{password}}"
        array_id: "{{array_id}}"
        sgname: "Ansible_SG"
