- name: "Add volumes to existing storage group"
  connection: local
  hosts: localhost
  vars:
    array_id: 000197600156
    password: smc
    sgname: Ansible_SG
    unispherehost: "192.168.123.1"
    universion: "90"
    user: smc
    verifycert: false

  tasks:
  - name: Create Host1
    dellemc_pmax_createhost:
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        verifycert: "{{verifycert}}"
        user: "{{user}}"
        password: "{{password}}"
        array_id: "{{array_id}}"
        initiator_list:
        - 10000000c98ffe4a
        - 10000000c98ffe53
        host_id: "AnsibleHost1"

