- name: "Provision Storage For DB Cluster"
  connection: local
  hosts: localhost
  vars:
    array_id: 000197600156
    password: smc
    sgname: Ansible_SG
    unispherehost: "192.168.123.1"
    universion: "90"
    user: smc
    verifycert: false

  tasks:
    - name: "Base Values for Task Add module Specific paramters"
      dellemc_pmax_addcascadedsg:
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        array_id: "{{array_id}}"
        user: "{{user}}"
        password: "{{password}}"
        verifycert: "{{verifycert}}"
        parent_sg: "Ansible_Parent_SG"
        child_sg: "Ansible_SG"

