- name: "Delete existing Storage Group"
  connection: local
  hosts: localhost
  vars:
    array_id: 000197600156
    password: smc
    sgname: Ansible_SG
    unispherehost: "192.168.123.1"
    universion: "90"
    user: smc
    verifycert: false

  tasks:
    - name: "Delete Storage Group"
      dellemc_pmax_delete_sg:
        array_id: "{{array_id}}"
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        user: "{{user}}"
        password: "{{password}}"
        verifycert: "{{verifycert}}"
        sgname: "Ansible_SG"
