- name: "Add volumes to existing storage group"
  connection: local
  hosts: localhost
  vars:
    array_id: 000197600156
    password: smc
    sgname: Ansible_SG
    unispherehost: "192.168.123.1"
    universion: "90"
    user: smc
    verifycert: false

  tasks:
  - name: "Gather only storage_groups and masking_views facts"
    dellemc_pmax_gather_facts:
      unispherehost: "{{unispherehost}}"
      universion: "{{universion}}"
      verifycert: "{{verifycert}}"
      user: "{{user}}"
      password: "{{password}}"
      array_id: "{{array_id}}"
      gather_subset:
      - storage_groups
