- name: Create SnapVX SnapShot of existing Storage Group
  hosts: localhost
  connection: local
  vars:
        unispherehost: '192.168.123.1'
        universion: "90"
        verifycert: False
        user: 'smc'
        password: 'smc'


  tasks:
    - name: "link snapshot to target sg"
      dellemc_pmax_manage_snap:
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        array_id: "000197600156"
        user: "{{user}}"
        password: "{{password}}"
        verifycert: "{{verifycert}}"
        sgname: "Ansible_SG"
        snapshotname: "Ansible_Snap"
        target_sgname: "Ansible_lnk_SG"
        action: "link"
